apiVersion: v1
kind: Service
metadata:
  name: service-meet-hack-redis
  labels:
    app: service-meet-hack-redis
spec:
  type: ClusterIP
  ports:
    - name: http-port
      protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    app: meet-hack-redis
