version: '3'

services:
#  front:
#    build:
#      context: .
#      dockerfile: ./docker/front/Dockerfile
#    container_name: hack-camp_vol5_2022-front
#    tty: true
#    volumes:
#      - ./front:/app/front
#    command: sh -c "cd /app/front && npm install && npm start"
#    ports:
#      - 3000:3000

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: hack-camp_vol5_2022-server
    env_file:
      - docker-compose.env
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./server:/go/src/github.com/Doer-org/hack-camp_vol5_2022
    depends_on:
      - db
    command: go run .

  db:
    container_name: hack-camp_vol5_2022-db
    build: ./docker/db
    ports:
      - 5432:5432
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d
      - ./db:/var/lib/postgresql/data
    env_file:
      - docker-compose.env
    restart: always
