version: '3'

services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: hack-camp_vol5_2022-server
    env_file:
      - docker-compose.env
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./server:/go/src/github.com/Doer-org/hack-camp_vol5_2022
    depends_on:
      - db
    command: go run .

  db:
    container_name: hack-camp_vol5_2022-db
    build:
      context: .
      dockerfile: ./db/Dockerfile
    ports:
      - 5432:5432
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
    env_file:
      - docker-compose.env
    restart: always

  proxy:
    container_name: hack-camp_vol5_2022-proxy
    build: 
      context: .
      dockerfile: ./proxy/Dockerfile
    volumes:
      - ./proxy/conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80