version: '3'

services:
  # front:
  #   build:
  #     context: ./front
  #     dockerfile: Dockerfile
  #   container_name: front-hack-camp_vol5_2022
  #   ports:
  #     - 3000:80
  #   tty: true

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server-hack-camp_vol5_2022
    env_file:
      - docker-compose.env
    tty: true
    depends_on:
      - db

  db:
    container_name: db-hack-camp_vol5_2022
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
    env_file:
      - docker-compose.env
    restart: always

  proxy:
    container_name: proxy-hack-camp_vol5_2022
    build: 
      context: ./proxy
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
      - 80:80
    volumes:
      - ./proxy/logs:/var/log/nginx

  redis:
    container_name: redis-hack-camp_vol5_2022
    build: 
      context: ./redis
      dockerfile: Dockerfile
    restart: always
    tty: true
    ports:
      - 6379:6379
    depends_on:
      - server
    # volumes:
    #   - /redis/data:/data
