apiVersion: apps/v1
kind: Deployment
metadata:
  name: meet-hack-proxy
spec:
  selector:
    matchLabels:
      app: meet-hack-proxy
  # replicas: 2
  template:
    metadata:
      labels:
        app: meet-hack-proxy
    spec:
      containers:
        - name: meet-hack-proxy
          image: gcr.io/meethack-dev-362310/meet-hack-proxy@sha256:f08f9485362d9161825d414eed6b4fe061c62e852b38cd87beb524f49d50d708
          imagePullPolicy: Always
          ports:
            - containerPort: 80
