apiVersion: v1
kind: Service
metadata:
  name: service-meet-hack-proxy
  labels:
    app: service-meet-hack-proxy
spec:
  type: LoadBalancer
  ports:
    - name: http-port
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: meet-hack-proxy
