apiVersion: v1
kind: Service
metadata:
  name: meet-hack-proxy
  labels:
    app: meet-hack-proxy
spec:
  selector:
    app: meet-hack-proxy
  ports:
    - name: http-port
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
