apiVersion: apps/v1
kind: Deployment
metadata:
  name: meet-hack
  labels:
    name: meet-hack
spec:
  # replicas: 3
  selector:
    matchLabels:
      app: meet-hack
  template:
    metadata:
      labels:
        app: meet-hack
    spec:
      containers:
      - name: meet-hack
        image: gcr.io/meethack-dev-362310/meet-hack@sha256:5d0921cbf7d978b4d7a0e84dd73924976bb822866fc7ca7f1afa8445b4b95816
        imagePullPolicy: Always
        ports:
          - containerPort: 80
