apiVersion: apps/v1
kind: Deployment
metadata:
  name: meet-hack
  labels:
    name: meet-hack
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meet-hack
  template:
    metadata:
      labels:
        app: meet-hack
    spec:
      containers:
      - name: meet-hack
        image: gcr.io/ecstatic-router-353016/meet-hack@sha256:079dd911a1f823896dfc4db2d5ca4acb980ce428449c784ea62531e641b12e7d
        imagePullPolicy: Always
        ports:
          - containerPort: 80
