apiVersion: v1
kind: Service
metadata:
  name: service-meet-hack
  labels:
    app: service-meet-hack
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: meet-hack
