apiVersion: v1
kind: Service
metadata:
  name: service-meet-hack-api
  labels:
    app: service-meet-hack-api
spec:
  type: ClusterIP
  ports:
    - name: http-port
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: meet-hack-api
