apiVersion: v1
kind: Service
metadata:
  name: meet-hack-api-service
spec:
  selector:
    app: meet-hack-api
  ports:
    - name: http-port
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
